name: amp

# PPO
num_mini_batches: 4
num_learning_epochs: 5
clip_param: 0.2
discount: 0.99
td_lambda: 0.95
lr: 5e-5
max_grad_norm: 1.0
use_clipped_value_loss: true
desired_kl: 0.01
value_loss_coef: 1.0
entropy_coef: 0.0

# AMP discriminator
num_disc_obs_steps: 10
discriminator_buffer_capacity: 200000
disc_replay_samples: 1000
disc_logit_reg: 0.01
disc_lr: 1e-4
discriminator_update_interval: 1 # They do 1
disc_num_updates: 5
disc_batch_size: 2048
disc_grad_penalty_coef: 5.0
disc_weight_decay: 0.0001

# Reward weights
disc_reward_lambda: 2.0
goal_reward_lambda: 1.0